using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Modbus")]
[assembly: AssemblyProductAttribute("NModbus")]
[assembly: InternalsVisibleToAttribute("Modbus.UnitTests")]
[assembly: InternalsVisibleToAttribute("DynamicProxyGenAssembly2")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("a2ec5378-e1b7-4bb0-b696-1c657407eeb9")]
[assembly: AssemblyVersionAttribute("1.4.0.3")]
[assembly: AssemblyFileVersionAttribute("1.4.0.3")]

